- hosts: all
  remote_user: ec2-user
  gather_facts: False

  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

  tasks:
    - name: Update apt cache
      raw: apt-get update

    - name: Ensure git and screen are installed
      raw: apt-get install -y screen git

    - git: 
        repo: "https://github.com/EmpireProject/Empire"
        version: dev
        dest: /root/empire
        update: yes

    - copy: 
        src: EmpireStartup.rc
        dest: /root/empire

    - copy: 
        src: empire-c2.service
        dest: /etc/systemd/system

    - name: Setup Empire
      command: /root/empire/setup/install.sh
      environment:
        STAGING_KEY: 'RANDOM'
      args:
        chdir: /root/empire
        
    - pause:
        seconds: 15