- hosts: all
  remote_user: ec2-user
  gather_facts: False

  tasks:
    - name: reload systemd daemon
      raw: systemctl daemon-reload

    - name: Start Empire in a screen session
      service: 
          state: started
          name: empire-c2.service

    - pause:
        seconds: 15

    - fetch: 
        src: /root/Empire_http80.ps1
        dest: stager.ps1
